name: "Rename Upm Package"
author: "PhantasmicDev"
description: "Renames and edits files to reflect a name change of a upm package."
branding:
  icon: "file-text"
  color: "white"

inputs:
  my-input:
    description: "Input Example"
    required: false

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
