name: Initialize

on:
  create:
  
jobs:
  initialize:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: octokit/request-action@v2.x
        id: repo-info
        with:
          route: GET /repos/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Initialize
        run: | 
          ACTION_NAME=$(echo "${{ github.event.repository.name }}" | sed 's/\b\([a-z]\)/\U\1/g; s/-/ /g')
          
          # Clear README.md and set title to new action name
          echo "# $ACTION_NAME" > README.md
          
          # Remove license
          rm -f LICENSE
          
          # Set the name entry
          sed -i "s/^name:.*/name: \"$ACTION_NAME\"/" action.yml
          
          # Set the author entry
          sed -i "s/^author:.*/author: \"${{ github.repository_owner }}\"/" action.yml
          
          # Set the description entry
          DESCRIPTION="${{ fromJson(steps.repo-info.outputs.data).description }}"
          sed -i "s/^description:.*/description: \"$DESCRIPTION\"/" action.yml
          
          # Delete initialization workflow file
          rm -f .github/workflows/initialize.yml
          
      - name: Commit Initialization
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Initialized
